spring:
  profiles:
    active: @profileActive@
  application:
    name: homework-tracker
  flyway:
    enabled: true


server:
  port: 4567

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: homework-tracker API
